# Alt küme üzerinde işlem yapmak

In [1]:
import numpy as np

In [2]:
a= np.random.randint(10,size=(5,5))

In [3]:
a

array([[4, 4, 1, 9, 5],
       [9, 7, 6, 1, 3],
       [0, 1, 9, 9, 7],
       [6, 7, 7, 7, 4],
       [4, 3, 2, 6, 6]])

In [6]:
alt_a=a[0:3,0:2]
alt_a

array([[4, 4],
       [9, 7],
       [0, 1]])

In [7]:
alt_a[0,0]=9999
alt_a[1,1]=888
alt_a


array([[9999,    4],
       [   9,  888],
       [   0,    1]])

In [8]:
a

array([[9999,    4,    1,    9,    5],
       [   9,  888,    6,    1,    3],
       [   0,    1,    9,    9,    7],
       [   6,    7,    7,    7,    4],
       [   4,    3,    2,    6,    6]])

#### İşlem yaptığımız arrayın ilk hali daha sonra bize lazım olacaksa kullanacaksak yani copy methoduyla klonunu oluşturmalıyız.

In [9]:
m= np.random.randint(10,size=(5,5))
m

array([[3, 5, 2, 1, 7],
       [8, 6, 1, 9, 2],
       [5, 7, 8, 2, 1],
       [7, 1, 7, 2, 6],
       [3, 9, 6, 8, 9]])

In [10]:
alt_b= m[0:3,0:2].copy()

In [11]:
alt_b

array([[3, 5],
       [8, 6],
       [5, 7]])

In [12]:
alt_b[0,0]=999

In [13]:
alt_b

array([[999,   5],
       [  8,   6],
       [  5,   7]])

In [14]:
m

array([[3, 5, 2, 1, 7],
       [8, 6, 1, 9, 2],
       [5, 7, 8, 2, 1],
       [7, 1, 7, 2, 6],
       [3, 9, 6, 8, 9]])