# Numpy çalışmaları

In [2]:
import numpy as np

####  1) numpy array oluşturma

In [3]:
np.array([11,33,55,77,99])

array([11, 33, 55, 77, 99])

In [4]:
a= np.array([32,78,56,41,53])

In [5]:
type(a)

numpy.ndarray

#### numpy sabit tip baskısı yapar

##### mesela bir tane ondalıklı geriye kalan dizinin öğelerini tamsayı olan bir dizi yazalım ve neler olacağına bakalım

In [8]:
np.array([1.3,8,81,98,43,89])

array([ 1.3,  8. , 81. , 98. , 43. , 89. ])

#### tip baskısından dolayı dizinin hepsini ondalıklı sayıya çevirdi numpy

##### ama ayarlama yapabilmekteyiz şöyleki:


In [11]:
np.array([1.3,2,5,3], dtype="int")

array([1, 2, 5, 3])

### 2- Sifirdan array olusturma

In [13]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [17]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [18]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
np.random.normal(10,4,(3,4))

array([[10.27899419, 11.6007527 , 10.0797457 ,  9.13130815],
       [ 5.30673973,  5.85789221,  7.77540395,  7.57855908],
       [ 6.1180158 ,  2.32769352, 10.91269948,  8.54763392]])

In [21]:
np.random.randint(0,10,(3,3))

array([[9, 8, 2],
       [1, 6, 3],
       [8, 0, 7]])