# Numpy çalışmaları

In [2]:
import numpy as np

####  1) numpy array oluşturma

In [3]:
np.array([11,33,55,77,99])

array([11, 33, 55, 77, 99])

In [4]:
a= np.array([32,78,56,41,53])

In [5]:
type(a)

numpy.ndarray

In [6]:
#numpy sabit tip baskısı yapar

In [7]:
## mesela bir tane ondalıklı geriye kalan dizinin öğelerini tamsayı olan bir dizi yazalım ve neler olacağına bakalım

In [8]:
np.array([1.3,8,81,98,43,89])

array([ 1.3,  8. , 81. , 98. , 43. , 89. ])

In [9]:
## tip baskısından dolayı dizinin hepsini ondalıklı sayıya çevirdi numpy

In [10]:
# ama ayarlama yapabilmekteyiz şöyleki


In [11]:
np.array([1.3,2,5,3], dtype="int")

array([1, 2, 5, 3])