# Matematiksel Islemler

In [2]:
import numpy as np

In [3]:
v= np.array([1,2,3,4,5])

In [4]:
v-1

array([0, 1, 2, 3, 4])

In [5]:
v*5

array([ 5, 10, 15, 20, 25])

In [7]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

#### biz burdaki matematiksel işlemleri yaptıkça ufunc adı verilen mekanizma çalışıyor

In [8]:
# örneğin ilk işlemde yaptığımız v-1 için birçok dönüşüm kullanılıyor.
# numpyden substract fonksiyonu gelip v vektörüne şu işlemi yapsın demek oluyoruz.

np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [9]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [11]:
np.multiply(v,2)

array([ 2,  4,  6,  8, 10])

In [12]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [13]:
v**2

array([ 1,  4,  9, 16, 25])

In [14]:
np.power(v,2)

array([ 1,  4,  9, 16, 25])

In [15]:
v%2

array([1, 0, 1, 0, 1])

In [17]:
np.mod(v,2)

array([1, 0, 1, 0, 1])

#### mutlak deger:

In [19]:
np.absolute(np.array([-3]))

array([3])

In [20]:
np.sin(360)

0.9589157234143065

In [21]:
np.cos(180)

-0.5984600690578581

In [22]:
v= np.array([1,2,3])

In [23]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [24]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [25]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [30]:
?np
#numpy dökümantasyonunu açar