# Yeniden şekillendirme (reshaping)

In [1]:
import numpy as np

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Reshape kullanarak 3,3 lük bir matrise çevirelim

In [8]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### bazı fonksiyonların isteklerini yerine getirmek için tek boyutlu ama 3.3lük matris formuna çevirmek gerekir.

In [10]:
a= np.arange(1,10)

In [11]:
a.ndim

1

In [15]:
b= a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
b.ndim

2