# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek

In [1]:
import numpy as np

In [2]:
a= np.arange(20,30)

In [3]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
a[0:3]

array([20, 21, 22])

In [5]:
a[:3]

array([20, 21, 22])

In [6]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [8]:
a[1::2]

array([21, 23, 25, 27, 29])

In [10]:
a[0::3]

array([20, 23, 26, 29])

#### İki boyutlu slice işlemleri

In [11]:
m =np.random.randint(10,size=(5,5))

In [12]:
m

array([[6, 3, 1, 8, 4],
       [6, 5, 3, 9, 6],
       [5, 9, 8, 9, 0],
       [4, 9, 4, 5, 4],
       [0, 5, 2, 6, 5]])

In [13]:
m[:,0]

array([6, 6, 5, 4, 0])

In [14]:
m[:,1]

array([3, 5, 9, 9, 5])

In [19]:
m

array([[6, 3, 1, 8, 4],
       [6, 5, 3, 9, 6],
       [5, 9, 8, 9, 0],
       [4, 9, 4, 5, 4],
       [0, 5, 2, 6, 5]])

In [18]:
m[0,:]

array([6, 3, 1, 8, 4])

In [20]:
m[0]

array([6, 3, 1, 8, 4])

In [21]:
m[1,:]

array([6, 5, 3, 9, 6])

In [23]:
m

array([[6, 3, 1, 8, 4],
       [6, 5, 3, 9, 6],
       [5, 9, 8, 9, 0],
       [4, 9, 4, 5, 4],
       [0, 5, 2, 6, 5]])

In [22]:
m[0:2,0:3]

array([[6, 3, 1],
       [6, 5, 3]])

In [24]:
m[::,:2]

array([[6, 3],
       [6, 5],
       [5, 9],
       [4, 9],
       [0, 5]])