# Array Sıralama (Sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [5]:
v

array([2, 1, 4, 3, 5])

In [7]:
v.sort()

In [8]:
v

array([1, 2, 3, 4, 5])

#### İki boyutlu array sıralama

In [19]:
m=np.random.normal(20,5,(3,3))

In [16]:
m

array([[29.04644524, 21.39303838, 22.05749168],
       [21.82356026, 25.21002819, 22.67626828],
       [18.06639151, 12.87783847, 19.24201463]])

In [17]:
np.sort(m,axis=1)

array([[21.39303838, 22.05749168, 29.04644524],
       [21.82356026, 22.67626828, 25.21002819],
       [12.87783847, 18.06639151, 19.24201463]])

In [18]:
np.sort(m,axis=0)

array([[18.06639151, 12.87783847, 19.24201463],
       [21.82356026, 21.39303838, 22.05749168],
       [29.04644524, 25.21002819, 22.67626828]])