# Index ile elamanlara erişmek

In [1]:
import numpy as np

In [2]:
a =np.random.randint(10,size =10)

In [3]:
a

array([1, 4, 7, 5, 2, 9, 3, 8, 9, 7])

In [4]:
a[0]

1

In [5]:
a[-1]

7

In [6]:
a[0]=100

In [7]:
a

array([100,   4,   7,   5,   2,   9,   3,   8,   9,   7])

#### İki boyutlu arrayde indexle elemana erişmek

In [8]:
m= np.random.randint(10,size=(3,5))

In [9]:
m

array([[8, 7, 1, 4, 2],
       [7, 3, 9, 8, 5],
       [2, 9, 8, 2, 8]])

In [10]:
m[0,0]

8

In [11]:
m[1,1]

3

In [12]:
m[2,1]

9

In [13]:
m[2,1]=99

In [19]:
m

array([[ 8,  7,  1,  4,  2],
       [ 7,  3,  2,  2,  5],
       [ 2, 99,  8,  2,  8]])

In [17]:
m[1,2]=2.2

In [18]:
m

array([[ 8,  7,  1,  4,  2],
       [ 7,  3,  2,  2,  5],
       [ 2, 99,  8,  2,  8]])