# NumPy ile iki bilinmeyenli denklem çözümü

In [1]:
import numpy as np

problem :

5 * x0 + x1 = 12
x0 + 3 * x1 = 10

In [4]:
a= np.array([[5,1],[1,3]])
b= np.array([12,10])

In [5]:
a

array([[5, 1],
       [1, 3]])

In [6]:
b

array([12, 10])

In [7]:
x= np.linalg.solve(a,b)

In [8]:
x

array([1.85714286, 2.71428571])